# Bun Configuration for WebDAV Backup

telemetry = false

[test]
# Configure preload scripts for tests
preload = ["./test-config/setup.ts"]

[install]
# Using text lockfile instead of binary for better version control compatibility
saveTextLockfile = true
registry = "https://registry.npmjs.org/"
